### ISSUE TITLE
VIN Decoding Details

### ISSUE THREAD

**Issue by jboarman** [abhionlyone/us-car-models-data#14]
I need to process a bunch of VINs to obtain the make, model and year.  Is that something that you are considering adding to this dataset?

Can you identify where this data is coming from now?

**Comment by abhilashiig** [comment]
Sorry for the late reply! I'm not getting enough time to spend on this project and probably will not be including any new fields in the near future @jboarman

**Comment by abhionlyone** [comment]
Sorry for the late reply! I'm not getting enough time to spend on this project and probably will not be including any new fields in the near future @jboarman
