### ISSUE TITLE
2022 Models

### ISSUE THREAD

**Issue by acp9191** [abhionlyone/us-car-models-data#9]
Hi there,

Thanks so much for maintaining this repo, it provides a ton of value. Would you be able to update the list with the latest 2022 models? It see it has the Chevrolet Bolt EV but not the [Bolt EUV](https://www.chevrolet.com/electric/bolt-euv). There may be more 2022 models as well that have come out since the last time this repo was updated in March.

Thanks!

**Comment by abhionlyone** [comment]
Hi @acp9191 , I've pushed an update for 2022 models.

Thank you,
Abhilash Reddy

**Comment by acp9191** [comment]
Thank you so much @abhionlyone!
